[workspace]
members = [
    "lo-core",
    "lo-web",
    "compile",
]

[profile.wasm_dev]
inherits = "dev"
panic = "abort"

[profile.wasm]
inherits = "release"
opt-level = 3
lto = true
panic = "abort"
debug = 0
