[package]
name = "lo-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dim-lo-core = { path = "../lo-core" }

[lib]
crate-type = ["cdylib"]